"""Serve the React bundle — from memory in the binary, from disk in dev.

Two sources, one behaviour, and the order matters:

  1. `webui_bundle` — a **generated, committed** Python module holding
     every asset as a gzip `bytes` literal. That is how the SPA ships
     inside one Nuitka `--onefile` binary with no external asset
     directory and no Node on either build host: Nuitka follows imports,
     so a module comes along for free while a data file needs its own
     `--include-data-files` entry to be right. theme.py:9-11 already
     states the same reasoning for the CSS and JS it holds as strings.
     Generated by scripts/gen_webui_bundle.py in Section 4.
  2. `webui/dist/` — what `npm run build` writes. Used when the module is
     absent, which is every developer checkout before that section, and
     is also the thing the generator reads.

If neither exists, `mount()` says so and mounts nothing. That is not a
failure: `npm run dev` serves the front end itself and proxies `/api`
here, which is the whole development loop.

**`/` and `/assets/*` are deliberately open.** The shell is what reads the
access token out of the URL fragment, so demanding the token before
handing over the shell would be a lock whose key is inside the room. It
is also useless without one — every route it calls is gated — so an
unauthenticated visitor gets a page that immediately says so.
"""

import gzip
import mimetypes
from pathlib import Path

from fastapi import HTTPException
from fastapi.responses import HTMLResponse, Response

from config import log

DIST = Path(__file__).resolve().parent / "webui" / "dist"

# Hashed filenames (index-a1b2c3d4.js) are content-addressed, so they can
# be cached forever. index.html cannot: it is what names them, and a
# browser holding yesterday's copy would ask for assets that are gone.
IMMUTABLE = "public, max-age=31536000, immutable"
NO_STORE = "no-cache"


def _bundle():
    """The generated module, or None before Section 4 has made one."""
    try:
        import webui_bundle
    except ImportError:
        return None
    return webui_bundle


def available() -> bool:
    return _bundle() is not None or (DIST / "index.html").is_file()


def _read(name: str) -> bytes | None:
    """One asset by its bundle-relative posix name, or None.

    The bundle wins over the directory so that a binary is never served a
    stale `webui/dist/` that happens to be sitting next to it — inside a
    onefile extraction there is no such directory, but a developer
    running the module form from a checkout has both.
    """
    bundle = _bundle()
    if bundle is not None:
        blob = bundle.ASSETS.get(name)
        return gzip.decompress(blob) if blob is not None else None
    target = DIST / name
    try:
        # Containment: a request for "../../config.py" must not resolve
        # out of the dist tree. Same rule as gallery_index.safe_path, over
        # a different root — and the reason it is repeated rather than
        # shared is that the two allow different extensions and share no
        # other logic.
        target = target.resolve()
        target.relative_to(DIST.resolve())
        return target.read_bytes()
    except (ValueError, OSError):
        return None


def mount(app) -> None:
    """Attach the SPA routes to a FastAPI app.

    Registered last, after every API route, because the catch-all below
    would otherwise swallow them: a single-page app has to answer *any*
    unmatched path with index.html so that a deep link like
    /edit/inpaint survives a reload.
    """
    if not available():
        log.info("No React bundle — serving the API only "
                 "(run `npm run dev` in webui/ for the front end)")
        return

    index = _read("index.html")
    if index is None:
        log.warning("The React bundle has no index.html — not mounting it")
        return

    @app.get("/assets/{name:path}", include_in_schema=False)
    def asset(name: str):
        data = _read("assets/" + name)
        if data is None:
            raise HTTPException(404, "No such asset.")
        media_type = mimetypes.guess_type(name)[0] or "application/octet-stream"
        return Response(data, media_type=media_type,
                        headers={"Cache-Control": IMMUTABLE})

    @app.get("/{path:path}", include_in_schema=False)
    def shell(path: str):
        """index.html for anything that is not an API route or an asset.

        The order of registration is what makes this safe: FastAPI matches
        routes in the order they were added, and every /api/v1 route was
        added before mount() was called. A path that reaches here is one
        the API did not claim.

        A file that really exists at the top of the bundle — favicon.svg,
        robots.txt — is served as itself; everything else is the shell,
        because it is a client-side route.

        The one exception is anything under `api/`. A mistyped or removed
        endpoint would otherwise come back as 200 and a page of HTML,
        which a fetch() reports as "unexpected token < in JSON" three
        layers away from the route that does not exist.
        """
        if path == "api" or path.startswith("api/"):
            raise HTTPException(404, "No such endpoint.")
        if path and "/" not in path:
            data = _read(path)
            if data is not None:
                media_type = (mimetypes.guess_type(path)[0]
                              or "application/octet-stream")
                return Response(data, media_type=media_type,
                                headers={"Cache-Control": NO_STORE})
        return HTMLResponse(index, headers={"Cache-Control": NO_STORE})

    source = "webui_bundle" if _bundle() is not None else str(DIST)
    log.info("Serving the React UI from %s", source)
