"""Serve the React bundle — from memory in the binary, from disk in dev.

Two sources, one behaviour, and the order matters:

  1. `webui_bundle` — a **generated, committed** Python module holding
     every asset as a gzip `bytes` literal. That is how the SPA ships
     inside one Nuitka `--onefile` binary with no external asset
     directory and no Node on either build host: Nuitka follows imports,
     so a module comes along for free while a data file needs its own
     `--include-data-files` entry to be right. The deleted theme.py:9-11
     stated the same reasoning for the CSS and JS it held as strings.
     Generated by scripts/gen_webui_bundle.py; kept honest by
     scripts/check_webui.py, which both build scripts run.
  2. `webui/dist/` — what `npm run build` writes. Read when the module is
     absent, which is a checkout that has run `npm run build` but not
     `make webui`, and is also the thing the generator reads.

If neither exists the routes are still mounted, and every page answers
with a short "front end not built" notice. That is deliberate: a fresh
clone with no node_modules has to be able to run `scripts/dryrun.py`, and
the failure it should see is a page that names the fix, not a 404 from a
route that was never registered.

**Deliberately NOT StaticFiles.** That class is filesystem-backed, and
inside a onefile extraction there is no directory to point it at. Serving
by hand is also what makes the two sources interchangeable and what makes
the gzip pass-through below possible.

Caching, and why it is not symmetrical
--------------------------------------
Vite content-addresses everything under `assets/` — `index-B21swU-0.js`
changes its name whenever it changes its bytes — so those can be cached
forever. `index.html` cannot: it is what names them, and a browser
holding yesterday's copy would ask for assets that no longer exist.

So index.html is `no-cache` + an `ETag`, and a conditional request gets a
304. Note `no-cache`, not `no-store`: "no-store" would forbid the browser
from keeping the copy at all, which makes it send no `If-None-Match`,
which makes the 304 path below dead code. `no-cache` is the one that
means "keep it, but revalidate every time" — the client cache is exactly
what is wanted here, because a onefile binary re-extracts on every launch
and has no warm server-side cache of its own to offer.

**`/` and `/assets/*` are deliberately open.** The shell is what reads the
access token out of the URL fragment, so demanding the token before
handing over the shell would be a lock whose key is inside the room. It
is also useless without one — every route it calls is gated — so an
unauthenticated visitor gets a page that immediately says so.
"""

import gzip
import hashlib
from pathlib import Path
from typing import NamedTuple

from fastapi import HTTPException, Request
from fastapi.responses import HTMLResponse, Response

from config import log

DIST = Path(__file__).resolve().parent / "webui" / "dist"

IMMUTABLE = "public, max-age=31536000, immutable"
REVALIDATE = "no-cache"

# Media types for the `webui/dist/` path, spelled out rather than taken
# from `mimetypes` — which on Windows answers from HKEY_CLASSES_ROOT,
# where `.js` is `text/plain` often enough to matter. A module script
# served as text/plain is refused outright by every browser, so the
# development loop would break on one machine and not another.
#
# scripts/gen_webui_bundle.py carries the same table for the assets it
# bakes in. Not shared: importing this module from there would pull in
# fastapi and config, and config creates directories at import time.
MEDIA_TYPES = {
    ".css": "text/css; charset=utf-8",
    ".html": "text/html; charset=utf-8",
    ".ico": "image/x-icon",
    ".jpeg": "image/jpeg",
    ".jpg": "image/jpeg",
    ".js": "text/javascript; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".map": "application/json; charset=utf-8",
    ".mjs": "text/javascript; charset=utf-8",
    ".png": "image/png",
    ".svg": "image/svg+xml",
    ".txt": "text/plain; charset=utf-8",
    ".webmanifest": "application/manifest+json",
    ".webp": "image/webp",
    ".woff": "font/woff",
    ".woff2": "font/woff2",
}
FALLBACK_TYPE = "application/octet-stream"

# Prefixes the SPA catch-all must never answer. A mistyped or removed
# endpoint would otherwise come back as 200 and a page of HTML, which a
# fetch() reports as "unexpected token < in JSON" three layers away from
# the route that does not exist. /media and /thumbs are named as well as
# /api because they are served under it (api.PREFIX + "/media/...") and a
# hand-written link that drops the prefix is the exact mistake this
# catches.
NOT_SPA = ("api", "media", "thumbs")

NOTICE = b"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>Ember - front end not built</title>
<style>
 body{background:#0e0e11;color:#e6e6ea;font:15px/1.6 system-ui,sans-serif;
      margin:0;display:grid;place-items:center;min-height:100vh}
 main{max-width:34rem;padding:2rem}
 h1{font-size:1.25rem;margin:0 0 1rem}
 code{background:#1c1c22;padding:.15rem .4rem;border-radius:4px}
 pre{background:#1c1c22;padding:.9rem 1rem;border-radius:8px;overflow-x:auto}
 p{color:#a8a8b3}
</style></head><body><main>
<h1>The front end is not built</h1>
<p>The API is running, but this build carries no React bundle. On a machine
with Node &ge; 20:</p>
<pre>make webui</pre>
<p>That runs <code>npm ci &amp;&amp; npm run build</code> in <code>webui/</code>
and regenerates <code>webui_bundle.py</code>, which is committed - so a
build host never needs Node.</p>
<p>To work on the front end itself, run <code>npm run dev</code> in
<code>webui/</code> and use Vite's port; it proxies the API back here.</p>
</main></body></html>
"""


class Asset(NamedTuple):
    """One servable file. `body` is gzip when `gzipped`, else raw."""

    body: bytes
    media_type: str
    etag: str
    gzipped: bool


def media_type(name: str) -> str:
    return MEDIA_TYPES.get(Path(name).suffix.lower(), FALLBACK_TYPE)


def _bundle():
    """The generated module, or None when it was never generated.

    Wrapped rather than imported at the top so that a checkout which has
    not run `make webui` still starts. Without this a fresh clone cannot
    run scripts/dryrun.py, and the traceback names webui_bundle - a file
    that is supposed to exist and has no obvious owner.
    """
    try:
        import webui_bundle
    except ImportError:
        return None
    return webui_bundle


def available() -> bool:
    """True when there is a real front end to serve, from either source."""
    return _bundle() is not None or (DIST / "index.html").is_file()


def _read(name: str) -> Asset | None:
    """One asset by its bundle-relative posix name, or None.

    The bundle wins over the directory so that a binary is never served a
    stale `webui/dist/` that happens to be sitting next to it - inside a
    onefile extraction there is no such directory, but a developer
    running from a checkout has both.
    """
    bundle = _bundle()
    if bundle is not None:
        found = bundle.ASSETS.get(name)
        if found is None:
            return None
        blob, kind, etag = found
        return Asset(blob, kind, etag, True)

    target = DIST / name
    try:
        # Containment: a request for "../../config.py" must not resolve
        # out of the dist tree. Same rule as gallery_index.safe_path, over
        # a different root - and the reason it is repeated rather than
        # shared is that the two allow different extensions and share no
        # other logic.
        target = target.resolve()
        target.relative_to(DIST.resolve())
        raw = target.read_bytes()
    except (ValueError, OSError):
        return None
    etag = 'W/"%s"' % hashlib.sha256(raw).hexdigest()[:32]
    return Asset(raw, media_type(name), etag, False)


def _respond(asset: Asset, request: Request, cache: str) -> Response:
    """Serve one asset, honouring If-None-Match and Accept-Encoding.

    The gzip stream is handed over untouched whenever the client will
    take it, which is every browser made this century. `gzip.decompress`
    is for the ones that will not - curl without --compressed, a health
    probe, a proxy that stripped the header - and costs a millisecond on
    a payload this size, which is the right way round: the common path is
    free and the rare one merely works.
    """
    if request.headers.get("if-none-match") == asset.etag:
        # 304 carries no body, but must repeat the validators, or the
        # next request arrives unconditional and the saving is undone.
        return Response(status_code=304, headers={
            "ETag": asset.etag, "Cache-Control": cache,
            "Vary": "Accept-Encoding",
        })

    headers = {"ETag": asset.etag, "Cache-Control": cache,
               "Vary": "Accept-Encoding"}
    body = asset.body
    if asset.gzipped:
        if "gzip" in request.headers.get("accept-encoding", ""):
            headers["Content-Encoding"] = "gzip"
        else:
            body = gzip.decompress(body)
    return Response(body, media_type=asset.media_type, headers=headers)


def mount(app) -> None:
    """Attach the SPA routes to a FastAPI app.

    Registered last, after every API route, because the catch-all below
    would otherwise swallow them: a single-page app has to answer *any*
    unmatched path with index.html so that a deep link like
    /edit/inpaint survives a reload. FastAPI matches in registration
    order, so a path that reaches here is one the API did not claim.
    """
    index = _read("index.html") if available() else None

    if index is None:
        if available():
            log.warning("The React bundle has no index.html - serving the "
                        "not-built notice instead")
        else:
            log.info("No React bundle - run `make webui`, or `npm run dev` "
                     "in webui/ for the development server")

        @app.get("/{path:path}", include_in_schema=False)
        def not_built(path: str):
            if path.split("/", 1)[0] in NOT_SPA:
                raise HTTPException(404, "No such endpoint.")
            return HTMLResponse(NOTICE, status_code=503,
                                headers={"Cache-Control": "no-store"})

        return

    @app.get("/assets/{name:path}", include_in_schema=False)
    def asset(name: str, request: Request):
        found = _read("assets/" + name)
        if found is None:
            raise HTTPException(404, "No such asset.")
        return _respond(found, request, IMMUTABLE)

    @app.get("/{path:path}", include_in_schema=False)
    def shell(path: str, request: Request):
        """index.html for anything that is not an API route or an asset.

        A file that really exists at the top of the bundle - favicon.svg,
        robots.txt - is served as itself; everything else is the shell,
        because it is a client-side route.
        """
        if path.split("/", 1)[0] in NOT_SPA:
            raise HTTPException(404, "No such endpoint.")
        if path and "/" not in path:
            found = _read(path)
            if found is not None:
                return _respond(found, request, REVALIDATE)
        # Re-read rather than closing over `index`: in development the
        # file on disk changes under a running server, and a stale shell
        # names asset hashes that no longer exist.
        current = _read("index.html") or index
        return _respond(current, request, REVALIDATE)

    bundle = _bundle()
    if bundle is not None:
        log.info("Serving the React UI from webui_bundle (%d assets, "
                 "built %s)", len(bundle.ASSETS),
                 getattr(bundle, "BUILT_AT", "?"))
    else:
        log.info("Serving the React UI from %s", DIST)
